ARG LARADOCK_PHP_VERSION
FROM ttungbmt/laradock-php-worker:${LARADOCK_PHP_VERSION}

MAINTAINER Truong Thanh Tung <ttungbmt@gmail.com>

RUN apk update && apk upgrade && apk add bash && rm -rf /var/cache/apk/*

